/**
 * The land masks for The Map: one per artwork, generated by
 * scripts/build-map-mask.mjs into ./masks. This module is the reader.
 *
 * See the generator for why a mask is committed rather than colours sampled
 * at test time. Short version: shadowed asphalt and dark water are the same
 * colour, and only connectivity to the picture's edge tells them apart.
 */

export type LandMask = {
  sha256: string;
  file: string;
  cell: number;
  width: number;
  height: number;
  /** One string per row of cells: `~` sea, `#` land. */
  rows: readonly string[];
};

/** True when this point on the artwork (in percent) is open water. */
export function isSea(mask: LandMask, x: number, y: number): boolean {
  const row = mask.rows[Math.min(mask.rows.length - 1, Math.max(0, Math.floor(((y / 100) * mask.height) / mask.cell)))];
  const col = Math.min(row.length - 1, Math.max(0, Math.floor(((x / 100) * mask.width) / mask.cell)));
  return row[col] === "~";
}

/** How much of an axis-aligned box on the artwork (all in percent) is open water, 0–1. */
export function seaFraction(mask: LandMask, x: number, y: number, w: number, h: number): number {
  let total = 0;
  let wet = 0;
  for (let dy = -h / 2; dy <= h / 2; dy += 0.5) {
    for (let dx = -w / 2; dx <= w / 2; dx += 0.5) {
      total++;
      if (isSea(mask, x + dx, y + dy)) wet++;
    }
  }
  return total === 0 ? 0 : wet / total;
}
