-- aOS Reporting Tool — the seeded metric list.
--
-- GENERATED FILE. Do not edit by hand: run
--   node scripts/generate-report-metrics-seed.mjs
-- which reads the tables in section 5 (and the explicitly listed section 6
-- launch fields) straight out of docs/reporting/reporting-tool-brief.md. The
-- schema test runs the generator with --check, so a hand edit here fails the
-- build rather than quietly disagreeing with the spec.
--
-- 174 metrics across 10 categories.

insert into public.report_metrics
  (key, category, label, input_type, unit, good_direction, entity_type, formula, sort_order)
values
  ('social_media_followers_at_month_end', 'social_media', 'Followers at month end', 'core', 'count', 'up', 'social_platform', null, 1),
  ('social_media_posts_published', 'social_media', 'Posts published', 'core', 'count', 'up', 'social_platform', null, 2),
  ('social_media_reach', 'social_media', 'Reach', 'core', 'count', 'up', 'social_platform', null, 3),
  ('social_media_views', 'social_media', 'Views', 'core', 'count', 'up', 'social_platform', null, 4),
  ('social_media_likes_plus_comments', 'social_media', 'Likes + comments', 'core', 'count', 'up', 'social_platform', null, 5),
  ('social_media_saves', 'social_media', 'Saves', 'core', 'count', 'up', 'social_platform', null, 6),
  ('social_media_shares', 'social_media', 'Shares', 'core', 'count', 'up', 'social_platform', null, 7),
  ('social_media_follows_gained', 'social_media', 'Follows gained', 'optional', 'count', 'up', 'social_platform', null, 8),
  ('social_media_profile_visits', 'social_media', 'Profile visits', 'optional', 'count', 'up', 'social_platform', null, 9),
  ('social_media_link_clicks', 'social_media', 'Link clicks', 'optional', 'count', 'up', 'social_platform', null, 10),
  ('social_media_dms_from_content', 'social_media', 'DMs from content', 'optional', 'count', 'up', 'social_platform', null, 11),
  ('social_media_keyword_comments', 'social_media', 'Keyword comments', 'optional', 'count', 'up', 'social_platform', null, 12),
  ('social_media_net_follower_growth', 'social_media', 'Net follower growth', 'calc', 'count', 'up', 'social_platform', 'Followers now − followers last month', 13),
  ('social_media_follower_growth', 'social_media', 'Follower growth %', 'calc', 'percent', 'up', 'social_platform', 'Net growth ÷ followers last month', 14),
  ('social_media_engagement_rate', 'social_media', 'Engagement rate', 'calc', 'percent', 'up', 'social_platform', '(Likes + comments + saves + shares) ÷ reach', 15),
  ('social_media_save_rate', 'social_media', 'Save rate', 'calc', 'percent', 'up', 'social_platform', 'Saves ÷ reach', 16),
  ('social_media_share_rate', 'social_media', 'Share rate', 'calc', 'percent', 'up', 'social_platform', 'Shares ÷ reach', 17),
  ('social_media_reach_per_post', 'social_media', 'Reach per post', 'calc', 'count', 'up', 'social_platform', 'Reach ÷ posts published', 18),
  ('social_media_profile_visit_to_follow', 'social_media', 'Profile visit to follow', 'calc', 'percent', 'up', 'social_platform', 'Follows gained ÷ profile visits', 19),
  ('trial_reels_trial_reels_posted', 'trial_reels', 'Trial reels posted', 'core', 'count', 'up', null, null, 1),
  ('trial_reels_new_followers_from_trial_reels', 'trial_reels', 'New followers from trial reels', 'core', 'count', 'up', null, null, 2),
  ('trial_reels_total_views', 'trial_reels', 'Total views', 'core', 'count', 'up', null, null, 3),
  ('trial_reels_profile_visits', 'trial_reels', 'Profile visits', 'core', 'count', 'up', null, null, 4),
  ('trial_reels_hours_spent_on_trial_reels', 'trial_reels', 'Hours spent on trial reels', 'core', 'hours', 'down', null, 'Filming, editing and posting', 5),
  ('trial_reels_buyers_from_trial_reels', 'trial_reels', 'Buyers from trial reels', 'optional', 'count', 'up', null, 'Anyone who bought and came from a trial reel', 6),
  ('trial_reels_average_views_per_reel', 'trial_reels', 'Average views per reel', 'calc', 'count', 'up', null, 'Total views ÷ trial reels posted', 7),
  ('trial_reels_follows_per_1k_views', 'trial_reels', 'Follows per 1,000 views', 'calc', 'ratio', 'up', null, 'New followers ÷ total views × 1,000', 8),
  ('trial_reels_profile_visit_to_follow_rate', 'trial_reels', 'Profile visit to follow rate', 'calc', 'percent', 'up', null, 'New followers ÷ profile visits', 9),
  ('trial_reels_followers_per_hour', 'trial_reels', 'Followers per hour', 'calc', 'ratio', 'up', null, 'New followers ÷ hours spent', 10),
  ('trial_reels_hours_per_buyer', 'trial_reels', 'Hours per buyer', 'calc', 'hours', 'down', null, 'Hours spent ÷ buyers', 11),
  ('email_list_size_at_month_end', 'email', 'List size at month end', 'core', 'count', 'up', null, null, 1),
  ('email_new_subscribers', 'email', 'New subscribers', 'core', 'count', 'up', null, null, 2),
  ('email_unsubscribes', 'email', 'Unsubscribes', 'core', 'count', 'down', null, null, 3),
  ('email_emails_sent', 'email', 'Emails sent', 'core', 'count', 'up', null, null, 4),
  ('email_average_open_rate', 'email', 'Average open rate', 'core', 'percent', 'up', null, null, 5),
  ('email_average_click_rate', 'email', 'Average click rate', 'core', 'percent', 'up', null, null, 6),
  ('email_sales_from_email', 'email', 'Sales from email', 'optional', 'count', 'up', null, null, 7),
  ('email_revenue_from_email', 'email', 'Revenue from email', 'optional', 'currency', 'up', null, null, 8),
  ('email_net_list_growth', 'email', 'Net list growth', 'calc', 'count', 'up', null, 'List size now − list size last month', 9),
  ('email_unsubscribe_rate', 'email', 'Unsubscribe rate', 'calc', 'percent', 'down', null, 'Unsubscribes ÷ list size last month', 10),
  ('email_click_to_open_rate', 'email', 'Click-to-open rate', 'calc', 'percent', 'up', null, 'Click rate ÷ open rate', 11),
  ('email_revenue_per_subscriber', 'email', 'Revenue per subscriber', 'calc', 'currency', 'up', null, 'Revenue from email ÷ list size', 12),
  ('funnels_landing_page_views', 'funnels', 'Landing page views', 'core', 'count', 'up', 'funnel', null, 1),
  ('funnels_opt_ins', 'funnels', 'Opt-ins', 'core', 'count', 'up', 'funnel', null, 2),
  ('funnels_sales_page_views', 'funnels', 'Sales page views', 'optional', 'count', 'up', 'funnel', null, 3),
  ('funnels_checkouts_started', 'funnels', 'Checkouts started', 'optional', 'count', 'up', 'funnel', null, 4),
  ('funnels_purchases', 'funnels', 'Purchases', 'core', 'count', 'up', 'funnel', null, 5),
  ('funnels_opt_in_rate', 'funnels', 'Opt-in rate', 'calc', 'percent', 'up', 'funnel', 'Opt-ins ÷ landing page views', 6),
  ('funnels_sales_page_conversion', 'funnels', 'Sales page conversion', 'calc', 'percent', 'up', 'funnel', 'Purchases ÷ sales page views', 7),
  ('funnels_checkout_completion', 'funnels', 'Checkout completion', 'calc', 'percent', 'up', 'funnel', 'Purchases ÷ checkouts started', 8),
  ('funnels_overall_conversion', 'funnels', 'Overall conversion', 'calc', 'percent', 'up', 'funnel', 'Purchases ÷ landing page views', 9),
  ('funnels_funnel_revenue', 'funnels', 'Funnel revenue', 'calc', 'currency', 'up', 'funnel', 'Purchases × linked offer price', 10),
  ('funnels_revenue_per_visitor', 'funnels', 'Revenue per visitor', 'calc', 'currency', 'up', 'funnel', 'Funnel revenue ÷ landing page views', 11),
  ('leads_conversions_new_leads_from_social', 'leads_conversions', 'New leads from social', 'core', 'count', 'up', null, null, 1),
  ('leads_conversions_new_leads_from_email', 'leads_conversions', 'New leads from email', 'core', 'count', 'up', null, null, 2),
  ('leads_conversions_new_leads_from_ads', 'leads_conversions', 'New leads from ads', 'pulled', 'count', 'up', null, 'From Ads: leads', 3),
  ('leads_conversions_new_leads_from_referral', 'leads_conversions', 'New leads from referral', 'core', 'count', 'up', null, null, 4),
  ('leads_conversions_new_leads_from_other', 'leads_conversions', 'New leads from other', 'optional', 'count', 'up', null, null, 5),
  ('leads_conversions_calls_booked', 'leads_conversions', 'Calls booked', 'core', 'count', 'up', null, null, 6),
  ('leads_conversions_calls_held', 'leads_conversions', 'Calls held', 'core', 'count', 'up', null, null, 7),
  ('leads_conversions_new_clients', 'leads_conversions', 'New clients', 'core', 'count', 'up', null, null, 8),
  ('leads_conversions_total_leads', 'leads_conversions', 'Total leads', 'calc', 'count', 'up', null, 'Sum of all sources', 9),
  ('leads_conversions_lead_source_split', 'leads_conversions', 'Lead source split', 'calc', 'percent', 'none', null, 'Each source ÷ total leads', 10),
  ('leads_conversions_call_show_up_rate', 'leads_conversions', 'Call show-up rate', 'calc', 'percent', 'up', null, 'Calls held ÷ calls booked', 11),
  ('leads_conversions_close_rate', 'leads_conversions', 'Close rate', 'calc', 'percent', 'up', null, 'New clients ÷ calls held', 12),
  ('leads_conversions_lead_to_client_rate', 'leads_conversions', 'Lead to client rate', 'calc', 'percent', 'up', null, 'New clients ÷ total leads', 13),
  ('ads_spend', 'ads', 'Spend', 'core', 'currency', 'none', 'ad_campaign', null, 1),
  ('ads_impressions', 'ads', 'Impressions', 'core', 'count', 'up', 'ad_campaign', null, 2),
  ('ads_link_clicks', 'ads', 'Link clicks', 'core', 'count', 'up', 'ad_campaign', null, 3),
  ('ads_leads', 'ads', 'Leads', 'core', 'count', 'up', 'ad_campaign', null, 4),
  ('ads_purchases', 'ads', 'Purchases', 'core', 'count', 'up', 'ad_campaign', null, 5),
  ('ads_revenue_from_ads', 'ads', 'Revenue from ads', 'core', 'currency', 'up', 'ad_campaign', null, 6),
  ('ads_reach', 'ads', 'Reach', 'optional', 'count', 'up', 'ad_campaign', null, 7),
  ('ads_cpm', 'ads', 'CPM', 'calc', 'currency', 'down', 'ad_campaign', 'Spend ÷ impressions × 1,000', 8),
  ('ads_ctr', 'ads', 'CTR', 'calc', 'percent', 'up', 'ad_campaign', 'Clicks ÷ impressions', 9),
  ('ads_cpc', 'ads', 'CPC', 'calc', 'currency', 'down', 'ad_campaign', 'Spend ÷ clicks', 10),
  ('ads_cost_per_lead', 'ads', 'Cost per lead', 'calc', 'currency', 'down', 'ad_campaign', 'Spend ÷ leads', 11),
  ('ads_cost_per_acquisition', 'ads', 'Cost per acquisition', 'calc', 'currency', 'down', 'ad_campaign', 'Spend ÷ purchases', 12),
  ('ads_roas', 'ads', 'ROAS', 'calc', 'ratio', 'up', 'ad_campaign', 'Revenue from ads ÷ spend', 13),
  ('client_experience_active_clients_at_start', 'client_experience', 'Active clients at start', 'pulled', 'count', 'none', null, 'Last month''s active at end', 1),
  ('client_experience_new_clients', 'client_experience', 'New clients', 'pulled', 'count', 'up', null, 'From Leads & Conversions', 2),
  ('client_experience_clients_who_left', 'client_experience', 'Clients who left', 'core', 'count', 'down', null, null, 3),
  ('client_experience_renewals_and_upsells', 'client_experience', 'Renewals and upsells', 'core', 'count', 'up', null, null, 4),
  ('client_experience_issues_raised', 'client_experience', 'Issues raised', 'core', 'count', 'down', null, 'Complaints, problems or things that went wrong for a client this month', 5),
  ('client_experience_testimonials_received', 'client_experience', 'Testimonials received', 'optional', 'count', 'up', null, null, 6),
  ('client_experience_programme_completions', 'client_experience', 'Programme completions', 'optional', 'count', 'up', null, null, 7),
  ('client_experience_repeat_engagers', 'client_experience', 'Repeat engagers', 'optional', 'count', 'up', null, null, 8),
  ('client_experience_active_clients_at_end', 'client_experience', 'Active clients at end', 'calc', 'count', 'up', null, 'Start + new − left', 9),
  ('client_experience_retention_rate', 'client_experience', 'Retention rate', 'calc', 'percent', 'up', null, '(Start − left) ÷ start', 10),
  ('client_experience_churn_rate', 'client_experience', 'Churn rate', 'calc', 'percent', 'down', null, 'Left ÷ start', 11),
  ('client_experience_upsell_rate', 'client_experience', 'Upsell rate', 'calc', 'percent', 'up', null, 'Renewals and upsells ÷ start', 12),
  ('client_experience_issues_per_10_clients', 'client_experience', 'Issues per 10 clients', 'calc', 'ratio', 'down', null, 'Issues raised ÷ active clients at end × 10', 13),
  ('client_experience_average_client_lifetime', 'client_experience', 'Average client lifetime', 'calc', 'months', 'up', null, '1 ÷ average monthly churn (last 12 months), shown once 3 months of data exist', 14),
  ('offers_units_sold', 'offers', 'Units sold', 'core', 'count', 'up', 'offer', null, 1),
  ('offers_revenue_this_month', 'offers', 'Revenue this month', 'core', 'currency', 'up', 'offer', 'Cash actually received, so discounts and payment plans are right', 2),
  ('offers_hours_spent_delivering', 'offers', 'Hours spent delivering', 'core', 'hours', 'down', 'offer', null, 3),
  ('offers_other_direct_costs', 'offers', 'Other direct costs', 'optional', 'currency', 'down', 'offer', 'Tools, contractors, materials for this offer', 4),
  ('offers_delivery_cost', 'offers', 'Delivery cost', 'calc', 'currency', 'down', 'offer', 'Hours × hourly cost + other direct costs', 5),
  ('offers_margin', 'offers', 'Margin', 'calc', 'percent', 'up', 'offer', '(Revenue − delivery cost) ÷ revenue', 6),
  ('offers_effective_hourly_rate', 'offers', 'Effective hourly rate', 'calc', 'currency', 'up', 'offer', '(Revenue − other direct costs) ÷ hours', 7),
  ('offers_share_of_total_revenue', 'offers', 'Share of total revenue', 'calc', 'percent', 'none', 'offer', 'Offer revenue ÷ total revenue', 8),
  ('offers_conversion_by_offer', 'offers', 'Conversion by offer', 'calc', 'percent', 'up', 'offer', 'Units sold ÷ linked funnel landing views (if a funnel is linked)', 9),
  ('financials_revenue_from_offers', 'financials', 'Revenue from offers', 'pulled', 'currency', 'up', null, 'Sum of all offers'' revenue', 1),
  ('financials_other_income', 'financials', 'Other income', 'optional', 'currency', 'up', null, null, 2),
  ('financials_fixed_costs', 'financials', 'Fixed costs', 'core', 'currency', 'down', null, 'Subscriptions, rent, software', 3),
  ('financials_variable_costs', 'financials', 'Variable costs', 'core', 'currency', 'down', null, 'Ads, contractors, fees', 4),
  ('financials_team_costs', 'financials', 'Team costs', 'core', 'currency', 'down', null, 'Salaries, VAs, freelancers', 5),
  ('financials_investment_spend', 'financials', 'Investment spend', 'optional', 'currency', 'none', null, 'Courses, coaching, events', 6),
  ('financials_cash_in_bank_at_month_end', 'financials', 'Cash in bank at month end', 'core', 'currency', 'up', null, null, 7),
  ('financials_total_revenue', 'financials', 'Total revenue', 'calc', 'currency', 'up', null, 'Offers + other income', 8),
  ('financials_total_costs', 'financials', 'Total costs', 'calc', 'currency', 'down', null, 'Fixed + variable + team + investment', 9),
  ('financials_profit', 'financials', 'Profit', 'calc', 'currency', 'up', null, 'Total revenue − total costs', 10),
  ('financials_profit_margin', 'financials', 'Profit margin', 'calc', 'percent', 'up', null, 'Profit ÷ total revenue', 11),
  ('financials_monthly_recurring_revenue', 'financials', 'Monthly recurring revenue', 'calc', 'currency', 'up', null, 'Sum of revenue from recurring offers', 12),
  ('financials_costs_as_percent_of_revenue', 'financials', 'Costs as % of revenue', 'calc', 'percent', 'down', null, 'Total costs ÷ total revenue', 13),
  ('financials_runway', 'financials', 'Runway', 'calc', 'months', 'up', null, 'Cash in bank ÷ average monthly costs (last 3 months)', 14),
  ('social_media_reach_from_followers', 'social_media', 'Reach from followers', 'optional', 'count', 'up', 'social_platform', null, 20),
  ('social_media_reach_from_non_followers', 'social_media', 'Reach from non-followers', 'optional', 'count', 'up', 'social_platform', null, 21),
  ('social_media_non_follower_reach', 'social_media', 'Non-follower reach %', 'calc', 'percent', 'up', 'social_platform', 'Reach from non-followers ÷ (reach from followers + reach from non-followers)', 22),
  ('funnels_order_bumps_taken', 'funnels', 'Order bumps taken', 'optional', 'count', 'up', 'funnel', null, 12),
  ('funnels_upsells_taken', 'funnels', 'Upsells taken', 'optional', 'count', 'up', 'funnel', null, 13),
  ('funnels_order_bump_take_rate', 'funnels', 'Order bump take rate', 'calc', 'percent', 'up', 'funnel', 'Order bumps ÷ purchases', 14),
  ('funnels_upsell_take_rate', 'funnels', 'Upsell take rate', 'calc', 'percent', 'up', 'funnel', 'Upsells ÷ purchases', 15),
  ('ads_profile_visits_from_ads', 'ads', 'Profile visits from ads', 'optional', 'count', 'up', 'ad_campaign', null, 14),
  ('offers_total_revenue_from_offers', 'offers', 'Total revenue from offers', 'calc', 'currency', 'up', null, 'Sum of all offers'' revenue', 10),
  ('offers_overall_margin', 'offers', 'Overall margin', 'calc', 'percent', 'up', null, '(Total revenue − total delivery cost) ÷ total revenue, weighted, not an average of offer margins', 11),
  ('offers_total_hours_spent_delivering', 'offers', 'Total hours spent delivering', 'calc', 'hours', 'down', null, 'Sum of all offers'' hours', 12),
  ('offers_overall_effective_hourly_rate', 'offers', 'Overall effective hourly rate', 'calc', 'currency', 'up', null, '(Total revenue − total other direct costs) ÷ total hours', 13),
  ('launches_sign_ups', 'launches', 'Sign-ups', 'core', 'count', 'up', null, null, 1),
  ('launches_live_attendees', 'launches', 'Live attendees', 'core', 'count', 'up', null, null, 2),
  ('launches_replay_watchers', 'launches', 'Replay watchers', 'optional', 'count', 'up', null, null, 3),
  ('launches_live_at_start', 'launches', 'Live at start', 'optional', 'count', 'up', null, null, 4),
  ('launches_live_at_pitch', 'launches', 'Live at pitch', 'optional', 'count', 'up', null, null, 5),
  ('launches_live_at_end_of_pitch', 'launches', 'Live at end of pitch', 'optional', 'count', 'up', null, null, 6),
  ('launches_show_up_rate', 'launches', 'Show-up rate', 'calc', 'percent', 'up', null, 'Day 1 live attendees ÷ sign-ups', 7),
  ('launches_day_by_day_drop_off', 'launches', 'Day-by-day drop-off', 'calc', 'percent', 'up', null, 'Each day''s attendees ÷ day 1 attendees', 8),
  ('launches_pitch_retention', 'launches', 'Pitch retention', 'calc', 'percent', 'up', null, 'Live at end of pitch ÷ live at start', 9),
  ('launches_percent_of_sign_up_goal', 'launches', 'Percent of sign-up goal', 'calc', 'percent', 'up', null, 'Sign-ups ÷ sign-up goal', 10),
  ('launches_email_list_size_sent_to', 'launches', 'Email list size sent to', 'core', 'count', 'up', null, null, 11),
  ('launches_email_open_rate', 'launches', 'Email open rate', 'core', 'percent', 'up', null, null, 12),
  ('launches_email_click_rate', 'launches', 'Email click rate', 'core', 'percent', 'up', null, null, 13),
  ('launches_email_unique_clicks', 'launches', 'Email unique clicks', 'core', 'count', 'up', null, null, 14),
  ('launches_average_open_rate_per_stage', 'launches', 'Average open rate per stage', 'calc', 'percent', 'up', null, 'Mean open rate of the stage''s emails', 15),
  ('launches_average_click_rate_per_stage', 'launches', 'Average click rate per stage', 'calc', 'percent', 'up', null, 'Mean click rate of the stage''s emails', 16),
  ('launches_sales_per_price_option', 'launches', 'Sales per price option', 'core', 'count', 'up', null, null, 17),
  ('launches_sales_from_stage', 'launches', 'Sales from stage', 'core', 'count', 'up', null, null, 18),
  ('launches_sales_from_email', 'launches', 'Sales from email', 'core', 'count', 'up', null, null, 19),
  ('launches_sales_from_dm', 'launches', 'Sales from DM', 'core', 'count', 'up', null, null, 20),
  ('launches_sales_from_ads', 'launches', 'Sales from ads', 'core', 'count', 'up', null, null, 21),
  ('launches_sales_from_referral', 'launches', 'Sales from referral', 'core', 'count', 'up', null, null, 22),
  ('launches_sales_from_unknown', 'launches', 'Sales from unknown', 'core', 'count', 'none', null, null, 23),
  ('launches_cash_collected_to_date', 'launches', 'Cash collected to date', 'core', 'currency', 'up', null, null, 24),
  ('launches_total_sales', 'launches', 'Total sales', 'calc', 'count', 'up', null, 'Sum of sales per price option', 25),
  ('launches_total_revenue', 'launches', 'Total revenue', 'calc', 'currency', 'up', null, 'Sum of (sales × price) per option, payment plans at full contract value', 26),
  ('launches_revenue_still_to_collect', 'launches', 'Revenue still to collect', 'calc', 'currency', 'down', null, 'Total revenue − cash collected', 27),
  ('launches_average_order_value', 'launches', 'Average order value', 'calc', 'currency', 'up', null, 'Total revenue ÷ total sales', 28),
  ('launches_percent_of_sales_goal', 'launches', 'Percent of sales goal', 'calc', 'percent', 'up', null, 'Total sales ÷ the Good, Better and Best targets', 29),
  ('launches_conversion_rate', 'launches', 'Conversion rate', 'calc', 'percent', 'up', null, 'Total sales ÷ live attendees of the main selling stage', 30),
  ('launches_dms_sent', 'launches', 'DMs sent', 'optional', 'count', 'up', null, null, 31),
  ('launches_dm_replies', 'launches', 'DM replies', 'optional', 'count', 'up', null, null, 32),
  ('launches_discovery_calls', 'launches', 'Discovery calls', 'optional', 'count', 'up', null, null, 33),
  ('launches_sales_calls_booked', 'launches', 'Sales calls booked', 'optional', 'count', 'up', null, null, 34),
  ('launches_sales_calls_closed', 'launches', 'Sales calls closed', 'optional', 'count', 'up', null, null, 35),
  ('launches_not_interested', 'launches', 'Not interested', 'optional', 'count', 'down', null, null, 36),
  ('launches_ad_spend', 'launches', 'Ad spend', 'optional', 'currency', 'none', null, null, 37),
  ('launches_ad_leads', 'launches', 'Ad leads', 'optional', 'count', 'up', null, null, 38),
  ('launches_ad_sales', 'launches', 'Ad sales', 'optional', 'count', 'up', null, null, 39),
  ('launches_reply_rate', 'launches', 'Reply rate', 'calc', 'percent', 'up', null, 'DM replies ÷ DMs sent', 40),
  ('launches_call_to_close_rate', 'launches', 'Call to close rate', 'calc', 'percent', 'up', null, 'Sales calls closed ÷ sales calls booked', 41),
  ('launches_cost_per_sign_up', 'launches', 'Cost per sign-up', 'calc', 'currency', 'down', null, 'Ad spend ÷ sign-ups', 42),
  ('launches_cost_per_sale', 'launches', 'Cost per sale', 'calc', 'currency', 'down', null, 'Ad spend ÷ total sales', 43),
  ('launches_launch_roas', 'launches', 'Launch ROAS', 'calc', 'ratio', 'up', null, 'Total revenue ÷ ad spend', 44),
  ('launches_live_attendees_needed', 'launches', 'Live attendees needed', 'calc', 'count', 'none', null, 'Sales goal ÷ conversion rate, rounded up', 45),
  ('launches_sign_ups_needed', 'launches', 'Sign-ups needed', 'calc', 'count', 'none', null, 'Live attendees needed ÷ show-up rate, rounded up', 46)
on conflict (key) do update set
  category = excluded.category,
  label = excluded.label,
  input_type = excluded.input_type,
  unit = excluded.unit,
  good_direction = excluded.good_direction,
  entity_type = excluded.entity_type,
  formula = excluded.formula,
  sort_order = excluded.sort_order;
